name: collatz-data-science
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy>=1.24.0
  - pandas>=2.0.0
  - matplotlib>=3.7.0
  - seaborn>=0.12.0
  - scipy>=1.10.0
  - scikit-learn>=1.3.0
  - jupyter>=1.0.0
  - jupyterlab>=4.0.0
  - ipykernel>=6.25.0
  - plotly>=5.15.0
  - bokeh>=3.2.0
  - streamlit>=1.25.0
  - flask>=2.3.0
  - numba>=0.57.0
  - dask>=2023.7.0
  - pytest>=7.4.0
  - pytest-cov>=4.1.0
  - black>=23.7.0
  - flake8>=6.0.0
  - isort>=5.12.0
  - tqdm>=4.65.0
  - click>=8.1.0
  - python-dotenv>=1.0.0
  - pip
  - pip:
    # Add any pip-only packages here if needed
    - streamlit-aggrid
    - dash